name: G-Pots
favicon: null
layout_spectrum: 0.738603200064972
typography_spectrum: 0.24626092589460313
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.024686853867024183
  lightness: 0.9302760020364076
  saturation: 0.726813581539318
  rhythmicContrast: 0.5796626331284642
purpose: []
